### ISSUE TITLE
filters, computed 支持上下文

### ISSUE THREAD

**Issue by harttle** [baidu/san-ssr#13]
目前 js ssr 中对于 function 的处理存在两点 trick：

1. 通过 .toString 来编译 Function。
2. 通过正则替换函数体中的 this.data.get。

导致以下代码无法正常工作：

```javascript
const { Component } from 'san'
const { sum } from 'some-util'

class MyComponent extends Component {
  computed: {
    foo: function(a, b) { return sum(a, b) }  // sum 未定义
  }
  someMethod () {
    const data = this.data
    return data.get('foo')  // data 未定义
  }
}
```

此外正则还有很多小问题，比如

* ES6 语法的 method 有毛病，没有 function 字样的 Function toString 后少个 `function`。
* 只替换了 computed 下方法，其他 method 没有替换：见 https://github.com/searchfe/san-ssr/issues/10

**Comment by l5oo00** [comment]
san 的官方文档里有[说明](https://baidu.github.io/san/tutorial/component/#%E8%AE%A1%E7%AE%97%E6%95%B0%E6%8D%AE):

> 计算数据的函数中只能使用 this.data.get 方法获取数据项的值，不能通过 this.method 调用组件方法，也不能通过 this.data.set 设置组件数据。

**Comment by harttle** [comment]
上述两个例子和提到的两个小问题都没有违反这个说明。`const data = this.data` 可能擦边球，字面上不算 `this.data.get`? @errorrik
