### ISSUE TITLE
San 组件 ts 校验不通过

### ISSUE THREAD

**Issue by PengXing** [baidu/san-ssr#27]
代码如下：

```typescript
class Component {
    static computed = {
        // aName() {
        //     return 'aName';
        // },
        aName() {
            const actName: string = this.data.get('actName');
            return actName || 'one';
        }
    };
}
```

报错信息如下：
![image](https://user-images.githubusercontent.com/527244/68919160-f6d24980-07ab-11ea-8b61-55fe294b6cee.png)

上面注释掉的写法不会报错

**Comment by harttle** [comment]
找到问题了，复现方式是让a组件引用b组件，不声明computed this类型，不禁用noImplicitThis的情况下，用ssr编译a组件。

解法1 关掉noImplicitThis，ts2php开这个选项是为了多数情况能正确编译应该开着

解法2 sanssr调用ts2php时候关掉noImplicitThis，同上，只是影响范围缩小到入口组件引用到的文件

解法3 编写组件是总是声明computed filters 这些静态成员的类型，写起来麻烦。但可以放到成员函数里就可以用父类类型约束了，但需要改san

解法4 ssr里在代码生成期间把所有组件之间引用干掉，问题是组件文件就只能提供组件了，不再有完整的esm功能

**Comment by harttle** [comment]
目前已经按照解法 3，把 thisArg 的类型（[SanSSRComponent](https://github.com/searchfe/san-ssr-target-php/blob/1db45535474750becff93e1583ac11984c274aaa/types/san-ssr-target-php/index.d.ts#L15)）在编译期（调用 ts2php 之前）注入给所有 filter 和 computed 函数。
