### ISSUE TITLE
编译期执行 computed 是不是太早了

### ISSUE THREAD

**Issue by harttle** [baidu/san-ssr#42]
**设计问题**。因为 `new Component` 时[执行了所有 computed](https://github.com/baidu/san/blob/70a881b4db293eafa3051cdd33f3ec4146bd3a5a/src/view/component.js#L248)，这一点上合理的因为组件就是用数据初始化的。那么：ssr 期间是否应该 new Component？

**实际问题**。因为 ssr 编译期间还不存在真实的数据，所有数据来自 initData，假数据上 computed 不一定能够正确执行。写组件时只有两个选择：

1. initData 写到非常详细和一致，和运行时数据一样。（看起来不合理）
2. computed 中判断各种数据是否存在，是否一致，来确保任何输入数据都可以兼容。（看起来也不合理）

类似 #41

**Comment by harttle** [comment]
@PengXing  @errorrik

**Comment by harttle** [comment]
补充例子：

```typescript
import { Component } from 'san'

class Component extends Component {
    static computed = {
        foo() {
            const url = this.data.get('url')
            const scheme1 = this.data.get('scheme')
            const scheme2 = this.data.get('scheme')
            if (!url) {
                return 'error: data malformed'
            }
            if (!scheme1) {
                return 'error: data malformed'
            }
            if (!scheme2) {
                return 'error: data malformed'
            }
            return url.replace(scheme1, scheme2)
        }
    }
}
```

**Comment by errorrik** [comment]
ssr 期间还是应该执行 computed 的。理由的话，其实这种场景很多的，computed本来就是计算数据。

编译期倒是没必要执行。但因为是编译期，所以执行了，也不会造成问题，我理解
