### ISSUE TITLE
support san.Components.parentComponent

### ISSUE THREAD

**Issue by bugkiwi** [baidu/san-ssr#52]
在子组件的 inited 函数中，需要获取父级组件的 inited 的一些状态与属性。（父子组件强耦合）
san.Component本身有此属性，希望能在 SSR 中支持。

https://github.com/baidu/san/blob/master/src/view/component.js#L116-L125

**Comment by harttle** [comment]
新增了对应的 test case：

https://github.com/baidu/san-ssr/blob/480105c9be5d07d972a0843b81bc8e014c894fa7/test/cases/parent-component/component.js#L3-L24

这个测试样例有个依赖：父子组件的 inited() 生命周期时序是父组件先发生，子组件后发生。因为目前 san 核心的行为也是这样，目前看 csr、ssr 是一致的。
