### ISSUE TITLE
运行时优化内存占用

### ISSUE THREAD

**Issue by cxtom** [baidu/san-ssr#71]
目前js版本的运行时，也会 require typescript、ts-morph 这些包，有些占用内存（typescript 代码有15m）

**Comment by harttle** [comment]
俩思路（由于第二个方案业务方升级比较顺滑，感觉都得做）：

- 提供 webpack 编译方案，类似 vuejs，做到运行时不 require san-ssr。
- san-ssr 按需加载 typescript。不太符合 lint，但这样改可以向下兼容。

**Comment by cxtom** [comment]
同感两个都得做

**Comment by harttle** [comment]
https://github.com/baidu/san-ssr/commit/50c7387a6ca99855ed32e15d47a888a5001e1733 支持了传入 script 和 template。配合使用的 loader 正在开发。

**Comment by harttle** [comment]
已经对 JavaScript 和 .san（San Script + San Template）支持输出 render 源码，见 #56 。

- 对于 .san 文件：.san->webpack(+san-ssr-plugin)->render 代码->运行时直接执行 render
- 其他场景： js/ts->webpack->render 代码 -> 运行时直接执行 render

二者都不再需要引用 san-ssr。但考虑到基于 JavaScript 的静态分析会限制一些语法的使用，原使用方式（运行时 require 到 ComponentClass->render函数->执行 render）仍然保留。
