### ISSUE TITLE
支持 SSR 期间不执行某些代码

### ISSUE THREAD

**Issue by harttle** [baidu/san-ssr#83]
两个例子：

- `import {axios} from './axios'`。没有对应的服务端实现的外部库。可以实现为 san-ssr 的 import/require 模块列表，在编译期移除。
- `inited() { axios.get('...') }`。不需要在服务端执行，但客户端需要执行的逻辑。可以实现为类似 `/* eslint-disable */`，在编译期移除对应的语句。

在 parse 阶段移除语句可能会引发 ts 的一些 lint 错误，需要在 ts2js 阶段把相应的 strict 检查设为 false。

**Comment by shirookie** [comment]
Re: 例2 `inited` 钩子
对于不应该在服务端执行的代码（如例子中的 `axios.get`、计时器 `setTimeout` 等），不应该放到 `inited` 钩子中，应该后移至 `mounted` （只在客户端执行）

**Comment by shirookie** [comment]
#86 已支持配置 removeModules 在编译时移除模块引用
